### PR TITLE
Project/autofocus

### PR DESCRIPTION
**Pull request by OscarAblinger**
This project, I feel like, fits here, as it does seem to help wildlife reservation quite a bit. It's a bit hard to guess the impact, though.

### CODE REVIEW

**Review by AdrienLemaire — COMMENTED** [review]
Isn't the contribution guide a requirement for listing a project in the list?
We could ask AutoFocus to write the page, and accept this PR following their action.

**Comment by OscarAblinger** [comment]
Hmmm, I'm not sure, if it is.
It definitely would mean a bad score, but they have issues tagged for beginners, so that's _something_.
We've also previously merged projects, whose contribution guide was mostly "This is how you open a PR".

I feel like, at this point we have enough projects to think about creating a metric anyways. (see #42)

If you don't want to add it without a contribution guide, that makes sense, too. Just reject the PR and we can revisit it if they add one

**Comment by OscarAblinger** [comment]
[I've opened an issue in the autofocus project](https://github.com/uptake/autofocus/issues/119)

**Comment by OscarAblinger** [comment]
Update: The contribution guide has now been merged into their dev branch: See [their PR](https://github.com/uptake/autofocus/pull/126#event-2828287305)

**Review by AdrienLemaire — APPROVED** [review]
@AblingerOscar I think this is our first success, you managed to influence a project! Amazing :tada:

**Comment by OscarAblinger** [comment]
> @AblingerOscar I think this is our first success, you managed to influence a project! Amazing

While I agree that that's a success, I think we've had similar success before with projects that added a license before (I think #28 had a similar, although smaller effect) :)

**Pull request merged**
